version: "3"

services:
  nodeserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        APPLICATION_SOCKET: "http://localhost:5001"
        INTERFACE_LANGUAGE: "ru"
        DEV_SHOW_REDUCERS: "true"
        SHOW_TEST_SCHEMAS: "true"
        USE_DEVTOOLS: "true"
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
