version: "3"

services:
  nodeserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        APPLICATION_SOCKET: "http://localhost:5001"
        INTERFACE_LANGUAGE: "ru"
        DEV_SHOW_REDUCERS: "true"
        SHOW_TEST_SCHEMAS: "true"
        USE_DEVTOOLS: "true"
    ports:
      - "0.0.0.0:3000:3000"
    restart: always
